"""Directly compiled if/else trees in C, with optional calibration branch probabilities.

Each split becomes ``if (go_left) ... else ...`` where ``go_left`` is
``x < t`` when missing values default right and ``!(x >= t)`` when they
default left (NaN fails both comparisons). Subtrees of height at most
``select_depth`` become nested conditional expressions, which Clang may lower
to conditional moves. Tree values are added to the accumulator immediately in
original order, as in ``compile_model``.
"""

from pathlib import Path
import time

import numpy as np

from .cgen import build, hexf, signature
from .model import Forest, Tree


def _cond(tree: Tree, node: int) -> str:
    x, t = f"row[{tree.feature[node]}]", hexf(tree.value[node])
    return f"!({x} >= {t})" if tree.default_left[node] else f"({x} < {t})"


def _expr(tree: Tree, node: int) -> str:
    if tree.left[node] == -1:
        return hexf(tree.value[node])
    return f"({_cond(tree, node)} ? {_expr(tree, tree.left[node])} : {_expr(tree, tree.right[node])})"


def _stmt(tree: Tree, node: int, counts, select_depth: int, indent: str) -> str:
    if tree.left[node] == -1 or tree.height[node] <= select_depth:
        return f"{indent}v = {_expr(tree, node)};\n"
    cond = _cond(tree, node)
    if counts is not None:
        nl, nr = counts[node]
        if nl + nr:
            # Clamp away from 0/1: the hint must stay a probability, not a promise.
            p = min(max(nl / (nl + nr), 0.001), 0.999)
            cond = f"__builtin_expect_with_probability({cond}, 1, {p:.6f})"
    return (f"{indent}if ({cond}) {{\n" + _stmt(tree, tree.left[node], counts, select_depth, indent + "  ")
            + f"{indent}}} else {{\n" + _stmt(tree, tree.right[node], counts, select_depth, indent + "  ")
            + f"{indent}}}\n")


def generate_c(forest: Forest, *, select_depth: int = 0, calibration: np.ndarray | None = None,
               entry: str = "predict_row", chained: bool = False) -> tuple[str, dict]:
    if isinstance(select_depth, bool) or not isinstance(select_depth, int) or not 0 <= select_depth <= 6:
        raise ValueError("select_depth must be an integer from 0 to 6")
    counts = forest.branch_counts(calibration) if calibration is not None else [None] * len(forest.trees)
    src = ["/* Generated by xgb_latency.direct; exact float32 thresholds and leaves. */\n",
           "#include <stdint.h>\n", signature(entry, chained)]
    if not chained:
        src.append(f"  float acc = {hexf(forest.base_margin)};\n")
    for t, tree in enumerate(forest.trees):
        src.append(f"  {{ /* tree {t} */ float v;\n" + _stmt(tree, 0, counts[t], select_depth, "    ")
                   + "    acc += v;\n  }\n")
    src.append("  return acc;\n}\n" if chained else "  *raw_margin = acc;\n}\n")
    return "".join(src), {"select_depth": select_depth, "profiled": calibration is not None}


def compile_direct(model_path: str | Path, output_dir: str | Path, *, select_depth: int = 0,
                   calibration: np.ndarray | None = None, cc: str = "clang", optimization: str = "O3") -> Path:
    """Exports ``void predict_row(const float *, float *)`` like ``compile_model``."""
    started = time.perf_counter()
    forest = Forest.load(model_path)
    source, stats = generate_c(forest, select_depth=select_depth, calibration=calibration)
    return build(source, forest, model_path, output_dir, lowering="direct", cc=cc, optimization=optimization,
                 started=started, extra={"exact_accumulation_order": True, **stats})
