"""VPred-style branch-free traversal over implicit complete trees (Asadi et al., 2014).

Each tree is padded to a complete binary tree of its group's height. A node's
children are found arithmetically, ``j = 2 * j + r``, where ``r`` is 1 when the
row goes right: ``(x >= t) | (isnan(x) & !default_left)``, the exact negation
of XGBoost's ``x < t`` / default routing. Padding below an early leaf copies
that leaf's value into every leaf slot beneath it, so the padding split's
direction is irrelevant and the result is exact.

Trees are evaluated ``lanes`` at a time with every lane's level-``l`` step
emitted back to back, so the out-of-order core overlaps the dependent loads of
different trees. Leaf values land in a per-tree buffer and are summed in the
original tree order afterwards, which keeps the float32 accumulation contract
even when ``group_by_height`` evaluates trees out of order.

Layouts:

* ``tree``: each tree's nodes are contiguous in BFS order.
* ``level``: within a lane group, level 0 of every tree, then level 1, ...
  (Forest-Packing-style interleaving of nodes that are fetched together).
"""

from pathlib import Path
import time

from .cgen import array, build, hexf, signature, sequential_sum
from .model import Forest, Tree

_DEFAULT_RIGHT = 1 << 31


def _complete(tree: Tree, height: int):
    """BFS-per-level records [(threshold, feature|flag)] and 2**height leaf values."""
    levels = [[None] * (1 << l) for l in range(height)]
    leaves = [0.0] * (1 << height)
    stack = [(0, 0, 0)]
    while stack:
        node, level, j = stack.pop()
        if level == height:
            if tree.left[node] != -1:
                raise AssertionError("tree taller than its padded height")
            leaves[j] = tree.value[node]
            continue
        if tree.left[node] == -1:  # Early leaf: route either way to copies of it.
            levels[level][j] = (0.0, 0)
            stack += [(node, level + 1, 2 * j), (node, level + 1, 2 * j + 1)]
        else:
            flag = 0 if tree.default_left[node] else _DEFAULT_RIGHT
            levels[level][j] = (tree.value[node], tree.feature[node] | flag)
            stack += [(tree.left[node], level + 1, 2 * j), (tree.right[node], level + 1, 2 * j + 1)]
    return levels, leaves


def plan_groups(forest: Forest, lanes: int, group_by_height: bool) -> list[list[int]]:
    order = list(range(len(forest.trees)))
    if group_by_height:
        order.sort(key=lambda t: (forest.trees[t].height[0], t))
    return [order[i:i + lanes] for i in range(0, len(order), lanes)]


def generate_c(forest: Forest, *, lanes: int = 8, layout: str = "tree",
               group_by_height: bool = True,
               entry: str = "predict_row", chained: bool = False) -> tuple[str, dict]:
    if isinstance(lanes, bool) or lanes not in (1, 2, 4, 8, 16, 32):
        raise ValueError("lanes must be 1, 2, 4, 8, 16 or 32")
    if layout not in {"tree", "level"}:
        raise ValueError("layout must be tree or level")
    if forest.num_feature >= _DEFAULT_RIGHT:
        raise ValueError("too many features")
    n_trees = len(forest.trees)
    groups = plan_groups(forest, lanes, group_by_height)
    nodes, leaves, out_index = [], [], []
    tree_base, leaf_base, group_base, group_leaf = [], [], [], []
    segments = []  # (height, first group, end group)
    padded = 0
    for g, members in enumerate(groups):
        height = max(forest.trees[t].height[0] for t in members)
        if segments and segments[-1][0] == height:
            segments[-1][2] = g + 1
        else:
            segments.append([height, g, g + 1])
        built = [_complete(forest.trees[t], height) for t in members]
        # Dummy lanes in a short last group evaluate a copy of lane 0 into a scratch slot.
        while len(built) < lanes:
            built.append(built[0])
        outs = members + [n_trees] * (lanes - len(members))
        out_index.extend(outs)
        padded += sum((1 << height) - 1 - sum(1 for c in forest.trees[t].left if c != -1) for t in members)
        group_base.append(len(nodes))
        group_leaf.append(len(leaves))
        if layout == "tree":
            for levels, tree_leaves in built:
                tree_base.append(len(nodes))
                for level in levels:
                    nodes.extend(level)
            for levels, tree_leaves in built:
                leaf_base.append(len(leaves))
                leaves.extend(tree_leaves)
        else:
            for level in range(height):
                for levels, _ in built:
                    nodes.extend(levels[level])
            for _, tree_leaves in built:
                leaves.extend(tree_leaves)
    if not nodes:
        nodes.append((0.0, 0))
    src = ["/* Generated by xgb_latency.vpred; exact float32 thresholds and leaves. */\n",
           "#include <stdint.h>\n\n",
           "typedef struct { float t; uint32_t fd; } node_t;\n",
           f"static const node_t NODE[] __attribute__((aligned(64))) = {{"
           + ",".join(f"{{{hexf(t)},{fd}u}}" for t, fd in nodes) + "};\n",
           array("float", "LEAF", leaves or [0.0], hexf),
           array("uint32_t", "OUT", out_index)]
    if layout == "tree":
        src += [array("uint32_t", "TBASE", tree_base), array("uint32_t", "LBASE", leaf_base)]
    else:
        src += [array("uint32_t", "GBASE", group_base), array("uint32_t", "GLEAF", group_leaf)]
    src.append(signature(entry, chained) + f"  float val[{n_trees + 1}];\n")
    for height, g0, g1 in segments:
        src.append(f"  for (uint32_t g = {g0}u; g < {g1}u; ++g) {{ /* height {height} */\n")
        if layout == "tree":
            src.append(f"    const uint32_t *tb = TBASE + g * {lanes}u, *lb = LBASE + g * {lanes}u;\n")
        else:
            src.append("    const uint32_t gb = GBASE[g], gl = GLEAF[g];\n")
        src.append("".join(f"    uint32_t j{w} = 0;\n" for w in range(lanes)))
        for level in range(height):
            for w in range(lanes):
                if layout == "tree":
                    index = f"tb[{w}] + {(1 << level) - 1}u + j{w}"
                else:
                    index = f"gb + {((1 << level) - 1) * lanes + w * (1 << level)}u + j{w}"
                src.append(f"    {{ const node_t *n = &NODE[{index}]; const float x = row[n->fd & 0x7fffffffu];\n"
                           f"      j{w} = 2 * j{w} + ((uint32_t)(x >= n->t) | ((uint32_t)(x != x) & (n->fd >> 31))); }}\n")
        for w in range(lanes):
            leaf = f"lb[{w}] + j{w}" if layout == "tree" else f"gl + {w * (1 << height)}u + j{w}"
            src.append(f"    val[OUT[g * {lanes}u + {w}u]] = LEAF[{leaf}];\n")
        src.append("  }\n")
    src.append(sequential_sum(forest, "val", chained) + "}\n")
    stats = {"lanes": lanes, "layout": layout, "group_by_height": group_by_height, "groups": len(groups),
             "height_segments": [s[0] for s in segments], "node_records": len(nodes),
             "padding_split_records": padded, "node_table_bytes": 8 * len(nodes), "leaf_table_bytes": 4 * len(leaves)}
    return "".join(src), stats


def compile_vpred(model_path: str | Path, output_dir: str | Path, *, lanes: int = 8, layout: str = "tree",
                  group_by_height: bool = True, cc: str = "clang", optimization: str = "O3") -> Path:
    """Exports ``void predict_row(const float *, float *)`` like ``compile_model``."""
    started = time.perf_counter()
    forest = Forest.load(model_path)
    source, stats = generate_c(forest, lanes=lanes, layout=layout, group_by_height=group_by_height)
    return build(source, forest, model_path, output_dir, lowering="vpred", cc=cc, optimization=optimization,
                 started=started, extra={"exact_accumulation_order": True, **stats})
